# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: setup-chromedriver
        uses: nanasess/setup-chromedriver@v2.0.0
       # Need to fetch reqs if needed
      - name: Install xvfb
        run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sleep 5
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
      - name: install dependencies
        run: pip install -r requirements.txt      
      - name: Running the Python script
        run: pytest
